### PR TITLE
Move lua binding wrappers into separate module

### PR DESCRIPTION
**Pull request by tarleb**
Increasing separation of pure haskell code, wrappers, and
raw C API functions.

### CODE REVIEW

**Comment by tarleb** [comment]
@sproctor feedback welcome

**Comment by sproctor** [comment]
I don't love this. It seems almost arbitrary which file a function definition ends up in. I could get behind this if there was a higher level API and a lower level API. newcfunction and freecfunction are firmly in the latter, IMO. What would this higher level API look like? Stack manipulation functions and convenient wrappers to execute Lua code? I'll do some thinking and try to come up with a proposal in the next few days.

**Comment by tarleb** [comment]
You have a point.  My idea was to put all functions that are directly related to `c_lua_*` functions into a separate module, but I guess you are right in that this detail is irrelevant to users.

The reason putting those functions into a separate module is that we can then have one module whose interface can be clearly defined, no matter which lua version was used. I'll see if I can think up a better way to achieve this.

**Comment by tarleb** [comment]
I pushed some changes that make this PR obsolete. The new module structure isn't optimal yet. Currently there is `Foreign.Lua.Functions` for (more or less) plain monadic wrappers of the C API functions, and `Foreign.Lua.Interop` for all things enabling data transfer between haskell and lua. I'm not very fond of the name of the latter. That module should be restructured; most of it would better fit into a  submodule of `Types`.

**Pull request closed without merging**
