### PR TITLE
Lua 5.3.2

### PR DESCRIPTION
**Pull request by reiddraper**
Sharing this, in case anyone is interested in Lua 5.3.2 support. Tests pass, but I've just done the minimum required to get everything building.

### CODE REVIEW

**Comment by reiddraper** [comment]
Rebased with master now. There's a test failure now that I rebased with 7e02c802a4cb5b87a27b98c1530adb969b9666eb -- haven't had a chance to look into this yet.

**Comment by sproctor** [comment]
The number of arguments returned by luaopen_base changed between 5.1 and 5.2. That broke the last test.

**Comment by osa1** [comment]
Would anyone here like to be the new maintainer of hslua? I made an announcement [here](https://groups.google.com/forum/#!msg/haskell-cafe/FXT4MkWWNso/4DNb-aT_BgAJ) and I'm still looking for a maintainer.

**Comment by sproctor** [comment]
I'm planning on using it for a project. If you want a co-maintainer for a while, I'd be willing to help out.

**Comment by osa1** [comment]
I have no time at all to work on this, I'm looking for a new main maintainer who'll take care of everything and decide on package's future (Lua 5.3 support etc.).

**Comment by afcowie** [comment]
> I have no time at all to work on this, I'm looking for a new main maintainer who'll take care of everything and decide on package's future (Lua 5.3 support etc.).

@ajnsit you've done work on top of **hslua** in **luautils**. I don't suppose you're interested in being maintainer. Same question goes to @reiddraper @raphaelcohn @stephenmac7 ...

**Comment by ajnsit** [comment]
@afcowie I haven't used HsLua at all recently, but I'm willing to help out (unless someone else more appropriate steps up).

**Comment by sproctor** [comment]
There's another breakage in 5.3. In the tests, inspect.lua prints out the Lua libs. The utf8 lib contains a string that is invalid utf8. https://www.lua.org/manual/5.3/manual.html#pdf-utf8.charpattern  The test uses hGetContents which chokes on that. I have a modified version of inspect.lua that escapes characters in strings greater than 127 and passes the test.

**Comment by tarleb** [comment]
Hi all, I'm currently working on Pandoc's Lua functionality and would be interested to help out as a (temporary) maintainer.  I'd like to help where I can, but would greatly appreciate the help from somebody more experienced with Lua and the FFI.  I created a new **hslua** organization and made @osa1 owner, such that he has full control of that organization.  @osa1, would transferring maintenance responsibilities to that organization be in your interest?

**Comment by osa1** [comment]
@tarleb, not sure why you created a new organization just for a single repo, but it's fine with me. I think pandoc is the biggest hslua user so far, so I think it'd make sense to give commit bits to pandoc devs. If decide to remove the org. and continue on this repo let me know and I'll give you commit bits. If you have any questions regarding Lua or FFI let me know.

**Comment by tarleb** [comment]
Ömer Sinan Ağacan <notifications@github.com> writes:

> @tarleb, not sure why you created a new organization just for a single repo

I assumed you'd want to transfer the repo as well, as you wouldn't have
to care about access management. If you don't mind those duties, then
I'd prefer to just keep the current repo. Fewer changes mean less
confusion; also issues, pull request won't have to be transfered.

> If decide to remove the org. and continue on this repo let me know and
> I'll give you commit bits. If you have any questions regarding Lua or
> FFI let me know.

I'll be happy to help if there are responsibilities which you'd like to
put on more (or shift to different different) shoulders. I also wouldn't
mind starting without priviledged access and just commit pull requests
to get feedback on new changes.

**Comment by osa1** [comment]
> I'll be happy to help if there are responsibilities which you'd like to put on more (or shift to different different) shoulders. I also wouldn't mind starting without priviledged access and just commit pull requests to get feedback on new changes.

I gave you commit bits. Feel free to make whatever changes you want to make and
add yourself as maintainer in cabal file etc. Let me know if you have any
questions regarding the implementation.

**Comment by tarleb** [comment]
Apologies for having hijacked this PR for off-topic discussions.  Back to the issue at hand: I did some ad-hoc changes to get the default tests to pass ([travis](https://travis-ci.org/tarleb/hslua/builds/186506612)). There are some remaining problems, possibly caused by cabal's way of handling UTF-8 strings.  But it mostly works.

One challenge I see is that switching to 5.3 would break LuaJIT support.  AFAIK, LuaJIT isn't compatible with 5.3 (yet).  My suggestion is to first do a release containing Lua 5.2.  This gives people the choice of using a newer version without having to drop LuaJIT support.

**Comment by osa1** [comment]
LuaJIT is the reason why I didn't update the library to use a more recent Lua. At least in my use case, I prefer 5.1 with LuaJIT over 5.2 or even 5.3 (which IMHO has more useful additions over Lua 5.1 like integers, new division operator etc.).

I'm no longer a user though, so I don't have a vote on this. FWIW I had a branch (I can't find it right now) that allowed both 5.1 and 5.2 with a Cabal flag, but it had awful amount of CPPs. So it's certainly possible, but it'll be painful for the maintainers.

**Comment by tarleb** [comment]
I'm closing this for now, as 5.3.2 is already outdated.  However, I'm going to start a new 5.3 branch and probably cherry-pick the second commit.

**Pull request closed without merging**
